### ISSUE TITLE
[BACK] Подключение приложения аутентификации.

### ISSUE THREAD

**Issue by mr-wolfoff** [nvrmndmnm/Loyalty-Program-App#13]
_Описание Фичи:_
> Создать приложение аутентификации Django, используя встроенные модели пользователя
> Создать эндпоинты для регистрации клиента и мерчанта
> Создать эндпоинты для авторизации клиента и мерчанта

**Мотивация**
> Возможность клиенту зарегистрироваться, для совершения дальнейших операций на нашем сервисе.

_Критерии приемки:_
> Приложение должно включать себя возможность регистрировать и производить авторизацию пользователя, путем номера телефона и пароля со стороны админки мерчанта и просто со стороны телеграм-бота

_Планируемое время:_
> 8 часов

**Comment by kaisarnur** [comment]
В целом я потратил 10 часов. https://www.youtube.com/watch?v=SbU2wdPIcaY здесь видео как создать кастомного юзера где телефон номера вместо username
