### ISSUE TITLE
Подключить проект к MySQL

### ISSUE THREAD

**Issue by nvrmndmnm** [nvrmndmnm/Loyalty-Program-App#2]
Добавить в проект настройки, необходимые для работы с MySQL. Если потребуется, в README репозитория описать шаги, которые нужно воспроизвести для создания подключения.
**Файл конфигурации с учётными данными не коммитить в репозиторий.**

**Comment by kaisarnur** [comment]
Шаг 1. Изменил настройки. Шаг 2 - Установил коннектор базы данных MySQL. Шаг 3 - Создал базу данных. Шаг 4 - Добавил подключение к базе данных MySQL в свое приложение. Шаг 5 - Проверил подключение MySQL к приложению.
На все мне ушло примерно 10 часов )

**Comment by nvrmndmnm** [comment]
В случае, если после запуска локального MySQL-сервера выдаётся ошика "EnvironmentError: mysql_config not found", нужно установить дополнительную библиотеку:
`sudo apt-get install libmysqlclient-dev`
