### ISSUE TITLE
[BACK] Настроить пароль клиента при регистрации

### ISSUE THREAD

**Issue by kaisarnur** [nvrmndmnm/Loyalty-Program-App#28]
_Описание Фичи:_

> В приложении accounts генерировать пароль

**Мотивация**

> Клиент должен иметь возможность после регистраций сбросить пароль и поставить свой

_Критерии приемки:_

> В приложении accounts при регистраций пользователя генерировать пароль и написать логику сброс пароля

_Планируемое время:_

> 1 день

**Comment by nvrmndmnm** [comment]
Нет необходимости, т.к. с пустым паролем пользователь всё равно не сможет залогиниться.
