### ISSUE TITLE
 Собрать данные о похожих приложениях

### ISSUE THREAD

**Issue by mr-wolfoff** [nvrmndmnm/Loyalty-Program-App#3]
До следующего митапа (10.12.2021. Пт.) найти на просторах интернета наиболее похожие сервисы (не обязательно локальные), выписать наиболее подходящие для нашего сервиса фитчи используемые в них, будет выноситься на обсуждение.

**Comment by skkv7** [comment]
[Похожие приложения Скоков.odt](https://github.com/nvrmndmnm/Loyalty-Program-App/files/7678951/default.odt)

**Comment by skkv7** [comment]
https://drive.google.com/file/d/1GMYr_RA93RGoo9YSvPTE3SWKVD7VLkCQ/view?usp=sharing
