### ISSUE TITLE
[BACK] При редиректе после регистрации выдаёт ошибку

### ISSUE THREAD

**Issue by nvrmndmnm** [nvrmndmnm/Loyalty-Program-App#51]
При регистрации нового пользователя выпадает ошибка:
DisallowedRedirect at /ru/accounts/create/
Unsafe redirect to URL with protocol 'accounts'

**Comment by kaisarnur** [comment]
def get_success_url(self):
    return reverse_lazy('accounts:login')

Добавил этот код и вроде работает

Ошибка была - Небезопасное перенаправление
