### ISSUE TITLE
[BACK] Дополнения в списке заказов пользователя

### ISSUE THREAD

**Issue by kaisarnur** [nvrmndmnm/Loyalty-Program-App#66]
- Время и дата покупки
- Сортировать по дате, показывать последнею покупку первой
- Фиксируется бесплатная покупка тут? Нужно показать и отметить что это был подарок
~~- Сейчас не показывается по конкретному клиенту~~ Исправлено

**Comment by nvrmndmnm** [comment]
Бесплатные покупки в этом списке не фиксируются, у них отдельная таблица.
