### ISSUE TITLE
[TELEGRAM-BOT] Возможность отправки QR-кода.

### ISSUE THREAD

**Issue by mr-wolfoff** [nvrmndmnm/Loyalty-Program-App#9]
_Описание Фичи:_
> При нажатии на команду “Сканировать QR-код” в менюшке бота, бот активирует камеру, клиент выполняет снимок QR-кода, затем бот отправляет снимок на сервер.

**Мотивация**
> Позволяет клиенту выполнять покупки внутри сервиса.

_Критерии приемки:_
> При нажатии на команду “Сканировать QR-код” в менюшке бота, бот должен активировать камеру, клиент должен выполнить снимок QR-кода, затем бот должен отправить снимок на сервер.

_Планируемое время:_
> 8 часов

**Comment by nvrmndmnm** [comment]
Т.к. Телеграм не поддерживает возможность сканирования QR-кода, решили сделать генерацию кода на стороне клиента и отправлять её в виде изображения.
